server:
  port: 8090
github:
  # Local testing only: replace the placeholder below temporarily, then remove it before committing.
#  token: ${GITHUB_TOKEN:PASTE_YOUR_GITHUB_TOKEN_HERE}
spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: mergewise-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.mergewise.dto.PRRequest